title: "BitsnBeyond"
author: "Vivek Mathew"
description: "Exploring life, family, and technology â€” one bit at a time." # This will show up in places like twitter, linkedin, etc, if you share your sites url as a post.
url: "https://www.bitsnbeyond.blog"
google_analytics: G-2JYVC25XD5
# Email / Social media user names used by the minima theme:
# All of these are optional and can be removed or commented out
email: "mr.vivek.mathew@mail.com"
twitter_username: "vivek_mathew"
github_username: "vmathew"
linkedin_username: "vjmathew"
#facebook_username: username
#flickr_username: username
#instagram_username: username
#pinterest_username: username
#youtube_username: username
#googleplus_username: +username

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

rss: rss

kramdown:
  syntax_highlighter_opts:
    disable: true
    
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag    # add this one for metadata
  - jekyll-paginate

paginate: 5
paginate_path: "/page:num"

kramdown:
  syntax_highlighter_opts:
    disable: true

titles_from_headings:
  strip_title: true
  collections: true

defaults:
  - scope:
      path: ""
      type: post
    values:
      layout: post
      tags: []
      categories: [tech]
